#####################
### LOOK AND FEEL ###
#####################

general {
    gaps_in = 3
    gaps_out = 5
    border_size = 1
    
    # Renkler Pywal'den geleceği için burası yedek kalabilir
    col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
    col.inactive_border = rgba(595959aa)

    resize_on_border = false
    allow_tearing = false
    layout = dwindle
}

decoration {
    rounding = 10
    rounding_power = 2

    active_opacity = 0.90 
    inactive_opacity = 0.80

    shadow {
        enabled = true
        range = 20
        render_power = 3
        color = rgba(1a1a1aee)
    }

    blur {
        enabled = true
        size = 6
        passes = 3
        vibrancy = 0.1696
        ignore_opacity = true 
        new_optimizations = true
        xray = false
    }
}

animations {
    enabled = yes
    
    # Bezier Eğrileri (Animasyonun hız grafiği)
    # wind: Rüzgar gibi hızlı başlayıp yavaşlayan
    # overshot: Hedefi biraz geçip geri gelen (yaylanma efekti)
    bezier = wind, 0.05, 0.9, 0.1, 1.05
    bezier = winIn, 0.1, 1.1, 0.1, 1.1
    bezier = winOut, 0.3, -0.3, 0, 1
    bezier = liner, 1, 1, 1, 1
    
    # Animasyon Kuralları
    animation = windows, 1, 6, wind, slide
    animation = windowsIn, 1, 6, winIn, slide
    animation = windowsOut, 1, 5, winOut, slide
    animation = windowsMove, 1, 5, wind, slide
    animation = border, 1, 1, liner
    animation = borderangle, 1, 30, liner, loop
    animation = fade, 1, 10, default
    animation = workspaces, 1, 5, wind
}

dwindle {
    pseudotile = true
    preserve_split = true
}

master {
    new_status = master
}

misc {
    force_default_wallpaper = -1
    disable_hyprland_logo = false
}
