##############################
### WINDOWS AND WORKSPACES ###
##############################

windowrule = opacity 1.0 1.0, match:class ^(firefox)$
windowrule = opacity 1.0 1.0, match:class ^(Zen Browser)$
windowrule = opacity 1.0 1.0, match:class ^(Brave-browser)$
windowrule = opacity 1.0 1.0, match:class ^(vlc)$
windowrule = opacity 1.0 1.0, match:class ^(mpv)$
windowrule = opacity 1.0 1.0, match:class ^(feh)$

windowrule = opacity 0.90 0.90, match:class ^(kitty)$
windowrule = opacity 0.90 0.90, match:class ^(code-oss)$
windowrule = opacity 0.90 0.90, match:class ^(VSCodium)$
windowrule = opacity 0.90 0.90, match:class ^(Rofi)$

windowrule = opacity 1.0 1.0, match:title ^(Picture-in-Picture)$
windowrule = pin on, match:title ^(Picture-in-Picture)$

windowrule = float on, match:class ^(kitty-float)$
windowrule = size 60% 60%, match:class ^(kitty-float)$
windowrule = center on, match:class ^(kitty-float)$
windowrule = animation popin, match:class ^(kitty-float)$

windowrule {
    name = suppress-maximize-events
    match:class = .*
    suppress_event = maximize
}

windowrule {
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false
    no_focus = true
}

windowrule {
    name = move-hyprland-run
    match:class = hyprland-run
    move = 20 monitor_h-120
    float = yes
}


windowrule = float on, match:class ^(kitty-float)$
windowrule = size 60% 60%, match:class ^(kitty-float)$
windowrule = center on, match:class ^(kitty-float)$
windowrule = animation popin, match:class ^(kitty-float)$

windowrule = opaque on, match:tag mat_mod