$primary_paletteKeyColor = 777777
$secondary_paletteKeyColor = 777777
$tertiary_paletteKeyColor = 7a7675
$neutral_paletteKeyColor = 777777
$neutral_variant_paletteKeyColor = 777777
$background = 141414
$onBackground = e3e3e3
$surface = 141414
$surfaceDim = 141414
$surfaceBright = 393939
$surfaceContainerLowest = 0e0e0e
$surfaceContainerLow = 1c1c1c
$surfaceContainer = 202020
$surfaceContainerHigh = 2a2a2a
$surfaceContainerHighest = 353535
$onSurface = e3e3e3
$surfaceVariant = 474747
$onSurfaceVariant = c6c6c6
$inverseSurface = e3e3e3
$inverseOnSurface = 303030
$outline = 919191
$outlineVariant = 474747
$shadow = 000000
$scrim = 000000
$surfaceTint = c6c6c6
$primary = c6c6c6
$onPrimary = 303030
$primaryContainer = 474747
$onPrimaryContainer = e2e2e2
$inversePrimary = 5e5e5e
$secondary = c6c6c6
$onSecondary = 303030
$secondaryContainer = 494949
$onSecondaryContainer = e2e2e2
$tertiary = cac6c5
$onTertiary = 32302f
$tertiaryContainer = 94908f
$onTertiaryContainer = 000000
$error = e4beb9
$onError = 601410
$errorContainer = 891c18
$onErrorContainer = e2e2e2
$primaryFixed = e2e2e2
$primaryFixedDim = c6c6c6
$onPrimaryFixed = 1c1c1c
$onPrimaryFixedVariant = 474747
$secondaryFixed = e2e2e2
$secondaryFixedDim = c6c6c6
$onSecondaryFixed = 1c1c1c
$onSecondaryFixedVariant = 464646
$tertiaryFixed = e2e2e2
$tertiaryFixedDim = cac6c5
$onTertiaryFixed = 1d1b1b
$onTertiaryFixedVariant = 494646
$term0 = 343434
$term1 = ef6263
$term2 = e4c5bc
$term3 = e6e6e6
$term4 = afa6bd
$term5 = d99a9d
$term6 = e6c2af
$term7 = d8d8d8
$term8 = a3a3a3
$term9 = ea908c
$term10 = e2dcdb
$term11 = f4f4f4
$term12 = c9bfb6
$term13 = e6b2b3
$term14 = e2d9d6
$term15 = ffffff
$rosewater = f2f2f2
$flamingo = e2e2e2
$pink = e3dbdb
$mauve = e7b3bd
$red = e8a1a4
$maroon = dfb4b4
$peach = e3c8c4
$yellow = f1f1f1
$green = e3dfde
$teal = f1ddbc
$sky = e3d6e8
$sapphire = e3bbe0
$blue = e9abc2
$lavender = e7c3cd
$klink = ae7697
$klinkSelection = ae7697
$kvisited = ba687a
$kvisitedSelection = bb6877
$knegative = dc6065
$knegativeSelection = dc6062
$kneutral = ea938b
$kneutralSelection = ea9388
$kpositive = ed9450
$kpositiveSelection = ed9450
$text = e3e3e3
$subtext1 = c6c6c6
$subtext0 = 919191
$overlay2 = 7e7e7e
$overlay1 = 6b6b6b
$overlay0 = 5a5a5a
$surface2 = 494949
$surface1 = 383838
$surface0 = 262626
$base = 141414
$mantle = 141414
$crust = 131313
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
