# Pywal Renklerini Çek
source = ~/.cache/wal/colors-hyprland.conf

general {
    no_fade_in = true
    no_fade_out = true
    hide_cursor = false
}

background {
    monitor =
    path = ~/Pictures/wallpapers/current_wallpaper.jpg
    color = $color7
    blur_passes = 2
    blur_size = 7
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = $foreground
    font_size = 120
    font_family = JetBrains Mono ExtraBold
    position = 0, -300
    halign = center
    valign = top
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%A, %d %B %Y")"
    color = $foreground
    font_size = 30
    font_family = JetBrains Mono
    position = 0, -200
    halign = center
    valign = top
}

input-field {
    monitor =
    size = 250, 60
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = $color1
    inner_color = $background
    font_color = $foreground
    fade_on_empty = false
    placeholder_text = <i>Enter your password...</i>
    hide_input = false
    position = 0, 120
    halign = center
    valign = bottom
}
