#  _   _                  _                 _  
# | | | |_   _ _ __  _ __| | __ _ _ __   __| | 
# | |_| | | | | '_ \| '__| |/ _` | '_ \ / _` | 
# |  _  | |_| | |_) | |  | | (_| | | | | (_| | 
# |_| |_|\__, | .__/|_|  |_|\__,_|_| |_|\__,_| 
#        |___/|_|                              
#  

source = ~/.config/hypr/SystemConfigs/Monitors.conf
source = ~/.config/hypr/SystemConfigs/Hardware.conf
source = ~/.config/hypr/SystemConfigs/Startup.conf

source = ~/.config/hypr/UserConfigs/Appearance.conf
source = ~/.config/hypr/UserConfigs/Keybinds.conf

source = ~/.cache/wal/colors-hyprland.conf

source = ~/.config/hypr/UserConfigs/WindowRules.conf
