#############################
### ENVIRONMENT VARIABLES ###
#############################

env = LIBVA_DRIVER_NAME,nvidia
env = XDG_SESSION_TYPE,wayland
env = GBM_BACKEND,nvidia-drm
env = _GLX_VENDOR_LIBRARY_NAME,nvidia
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = XCURSOR_THEME,Bibata-Modern-Ice

cursor {
  no_hardware_cursors = true
}

#############
### INPUT ###
#############

input {
    kb_layout = us,tr
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1
    sensitivity = 0

    touchpad {
        natural_scroll = false
    }
}

gesture = 3, horizontal, workspace
gesture = 3, down, fullscreen
gesture = 3, up, float

device {
    name = epic-mouse-v1
    sensitivity = -0.5
}
