exec-once = waybar &
# exec-once = caelestia shell
exec-once = wl-paste --watch cliphist store
exec-once = swaync
exec-once = swww-daemon
exec-once = gnome-keyring-daemon --start --components=secrets
